### ISSUE TITLE
Mnemo to private keys

### ISSUE THREAD

**Issue by PhilippeR26** [paulmillr/scure-starknet#6]
Hello Paul,
I have a code written with an old ethers.js v5.5.0 lib, that is able to convert the passPhrase of one of the most used Starknet Wallet to a list of private keys.
It works perfectly, but I would like to have something working with your @scure libs. Unfortunately, I don't find the way to convert the code.
The ethers.js code :
```typescript
import { BigNumber, utils, Wallet,  } from "ethers"; //v5.5.0
import * as mStark from '@scure/starknet';

const mnemonic = "inquiry tuition toe harvest vanish dress doctor maid divorce mystery cross loyal";
const wallet = Wallet.fromMnemonic(mnemonic)
const secret = wallet.privateKey;
const masterNode = utils.HDNode.fromSeed(BigNumber.from(secret).toHexString());
const baseDerivationPath = "m/44'/9004'/0'/0/";
for (let i = 0; i < 2; i++) {
        const path = baseDerivationPath + String(i);
        const childNode = masterNode.derivePath(path)
        const groundKey = "0x" + mStark.grindKey(childNode.privateKey)
        console.log("Account #",i,"\nPrivate Key =", groundKey, "\n", BigInt(groundKey));
}
```
Answer for index 0 is `0x40021c889366ff205847e1531fa07e12a01649e37c2e77827cbad4dc8a71f97`. It's conform to the output of the Starknet Wallet.

I tried several conversions to scure, without success :
```typescript
import * as mStarknet from '@scure/starknet';
import * as bip32 from '@scure/bip32';
import * as bip39 from '@scure/bip39';

const mnemonic = "inquiry tuition toe harvest vanish dress doctor maid divorce mystery cross loyal";
const hdKey = bip32.HDKey.fromMasterSeed(bip39.mnemonicToSeedSync(mnemonic))
const pathBase = "m/44'/9004'/0'/0/";
for (let i = 0; i < 2; i++) {
        const path = pathBase + String(i);
        const hdKey2 = hdKey.derive(path);
        const pvk = hdKey2.privateKey as Uint8Array;
        const groundKey = "0x" + mStarknet.grindKey(pvk);
        console.log("privateKey =", groundKey, "\n", BigInt(groundKey));
    }
```
Could you help me ?

**Comment by paulmillr** [comment]
bip39 is fine, but bip32 is not.

You need to fork bip32 and replace secp256k1 with stark curve. It should be simple.

**Comment by PhilippeR26** [comment]
I made this fork : https://github.com/PhilippeR26/scure-bip32/tree/Starknet
I added :
```typescript
import { _starkCurve} from '@scure/starknet';
```
and  replaced all `secp` by  `_starkCurve`.

I have this error : 
```
Error: Invalid private key
    at new HDKey (/D/crypto/scure-bip32/index.ts:160:15)
    at Function.fromMasterSeed (/D/crypto/scure-bip32/index.ts:97:12)
```

With ethers v5.5.0, I have :
```typescript
const entropy = hdnode.mnemonicToEntropy(mnemonic);
```
Result :
```
0x74dd478e34bf148550143040124cd042
```
Same result with :
```typescript
const entropy: Uint8Array = bip39.mnemonicToEntropy(mnemonic, english);
```
So the problem is not there.

I have some doubt about these constants : 
```typescript
const MASTER_SECRET = utf8ToBytes('Bitcoin seed');
// Bitcoin hardcoded by default
const BITCOIN_VERSIONS: Versions = { private: 0x0488ade4, public: 0x0488b21e };
export const HARDENED_OFFSET: number = 0x80000000;
```
Could it be there?

**Comment by PhilippeR26** [comment]
In addition :
In the ethers code, I found a salt, set to "mnemonic".
So I modified the code to : 
```typescript
const hdKey = bip32s.HDKey.fromMasterSeed(bip39.mnemonicToSeedSync(mnemonic,"mnemonic"))
```
But same error...

**Comment by paulmillr** [comment]
BIP32 standard was made for secp256k1 (btc, eth). Stark curve has much smaller order, which means many private keys from $2^256$ keyspace are invalid. So, the error is correct.

So you can't naïvely replace one with other, it requires further research.

See SLIP-0010 and ERC-2333 for standards which tackle similar problems.

**Comment by PhilippeR26** [comment]
Thanks for the answer.
What is strange is that it works perfectly in an old Ethers version....

**Comment by PhilippeR26** [comment]
Should be 0x40021c889366ff205847e1531fa07e12a01649e37c2e77827cbad4dc8a71f97

**Comment by paulmillr** [comment]
good to hear
