### ISSUE TITLE
Code observations and questions about signature validation

### ISSUE THREAD

**Issue by thiagodeev** [paulmillr/scure-starknet#7]
Hi @paulmillr. First of all, congratulations, and thank you for this amazing work!
I got here when debugging the starknet.js library to comprehend how the private keys and addresses were generated, and how to validate a signature. I tried to validate an already submitted Sepolia transaction using the starknet-js 'ec.starkCurve.verify' function to confirm my understanding but it returned 'false'. So I got in the @scure npm, and on the README.md from this repo, and tried to run your examples in the [Curve](https://github.com/paulmillr/scure-starknet?tab=readme-ov-file#curve) section, but I got some errors.

- First, it will be good to include `import { deepStrictEqual } from 'assert';` or `const { deepStrictEqual } = require("assert");` here too because the [codelines](https://github.com/paulmillr/scure-starknet/blob/main/README.md?plain=1#L43) containing the 'deepStrictEqual' function didn't work without it.

https://github.com/paulmillr/scure-starknet/blob/f1be2ea0a634856f1c87d15e60a26905b0ca3e5b/README.md?plain=1#L28

- Second, the 'fromHex' method didn't exist in the 'Signature' class, it's from the 'Point' class. Also, the sig variable itself is a 'SignatureType' variable, so directly assigning it this way: `const { r, s } = sig;` is enough to get the 'r' and 's' values.

https://github.com/paulmillr/scure-starknet/blob/f1be2ea0a634856f1c87d15e60a26905b0ca3e5b/README.md?plain=1#L42
<be>
Now my question:
After overcoming these issues I tried to validate my already deployed Sepolia transaction, so I called the `starknet.verify(sig, messageHash, publicKey)` function passing the signature and hash from my Sepolia transaction, and passing my publicKey directly as a hexadecimal string, but returned 'false', so I debugged to comprehend. Doing that, I find out in [this line](https://github.com/paulmillr/scure-starknet/blob/main/index.ts#L112) that the 'verify' function calls the '@noble/curve' library to converts the 'publicKey' parameter that I passed (a '0x + 64 length hexadecimal number, a standard Starknet public key)  to a 'Uint8Array' of length 32, but a final step on the validation calls [this](https://github.com/paulmillr/noble-curves/blob/4007ee975bcc6410c2e7b504febc1d5d625ed1a4/src/abstract/weierstrass.ts#L727) function that verifies if the public key Uint8Array has length 33 or 65, which is not the case (it's 32) and so the verification fails.
I noticed that if I call the 'starknet.getPublicKey' function passing my private key as a parameter I get a 65 length Uint8Array, and passing this variable through the 'starknet.verify' function as my public key works, it returns 'true'! Why that? Is that related to the fact that a Starknet public key (like the one I used, a '0x' + 64 length hexadecimal number) is just the X of a total of X and Y that compose the 'real' public key derived from a private key, and so, it cannot verify the transaction with this 'incomplete' key?

Please help me to understand this, and forgive me if I misunderstood something. Some things are still new to me. Thanks.

**Comment by paulmillr** [comment]
Hi

For the doc improvements: please submit PR.

As for the verification: there are some custom routines which are stark-specific:

https://github.com/paulmillr/scure-starknet/blob/f1be2ea0a634856f1c87d15e60a26905b0ca3e5b/index.ts#L24-L38

https://github.com/paulmillr/scure-starknet/blob/f1be2ea0a634856f1c87d15e60a26905b0ca3e5b/index.ts#L55-L60

https://github.com/paulmillr/scure-starknet/blob/f1be2ea0a634856f1c87d15e60a26905b0ca3e5b/index.ts#L118-L122

https://github.com/paulmillr/scure-starknet/blob/f1be2ea0a634856f1c87d15e60a26905b0ca3e5b/index.ts#L139-L141

**Comment by thiagodeev** [comment]
Thanks for answering @paulmillr!
A last question: could you tell me why the keys need to be padded with 0 to reach the 64 length? Why aren't they fixedly generated with 64-length without needing to be padded?

**Comment by paulmillr** [comment]
That's how Starknet spec / other implementations worked. The repo simply followed them.
